services:
  postgres:
    build:
      context: ./services/postgresql/image/
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./config/db/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
volumes:
  pg_data: