services:  
  nginx:
    build:
      context: ./services/nginx/image/
      dockerfile: Dockerfile.dev
    networks:
      - backend
    depends_on:
      ckan-dev:
        condition: service_healthy
    ports:
      - "${NGINX_SSLPORT_HOST}:${NGINX_SSLPORT}"
      # - "0.0.0.0:${NGINX_SSLPORT_HOST}:${NGINX_SSLPORT}"