---
services:
  solr:
    build:
      context: ./services/solr/image
      args:
        CKAN_BRANCH: ckan-${CKAN_VERSION}
    networks:
      - solrnet
    env_file:
      - ./config/solr/.env
      - ./.global-env
    volumes:
      - solr_data:/var/solr
    healthcheck:
      test: ["CMD-SHELL", "/opt/solr/bin/solr", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  solr_data: