#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ckan_test OWNER $CKAN_DB_USER ENCODING 'UTF8';
    CREATE DATABASE datastore_test OWNER $CKAN_DB_USER ENCODING 'UTF8';
EOSQL
