---
services:
  redis:
    image: redis:${REDIS_VERSION}
    networks:
      - redisnet
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s